name: MSBuild

on:
  push:
    branches: [ "retropc" ]
  pull_request:
    branches: [ "retropc" ]

env:
  SOLUTION_FILE_PATH: src
  BUILD_CONFIGURATION: Release
  TARGET_PLATFORM: x64
  WINDOWS_SDK_VERSION: 10.0.19041.0
  
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.TARGET_PLATFORM}} /p:WindowsTargetPlatformVersion=${{env.WINDOWS_SDK_VERSION}} ${{env.SOLUTION_FILE_PATH}}

    - uses: actions/upload-artifact@v3
      with:
        path: src/x64/Release/Winfile.exe
